- src/List.elm
- src/Native/List.js
- tests/Test/List.elm
1. Remove unused `last` and `nth`.
2. Implement `reverse` in Elm because it is probably faster and creates less garbage than converting too and from array. The new implementation will iterate over the list only once.
> List cleanup

- src/Native/Graphics/Collage.js
See discussion on #862, especially https://github.com/elm-lang/elm-compiler/issues/862#issuecomment-68155239.
This merits careful review because I don't know why the `kid.getContext` check that I'm removing was there in the first place. @etaque reports that this change fixes the issue.
> Fix disappearing HTML elements, Fixes #862

- src/Graphics/Collage.elm
Had some trouble with this while learning how to use "collage"; seems like the co-ordinate system is not actually explicitly specified anywhere in the library - only implicitly by the examples, as well as in release notes for a previous version of Elm.
> Document the collage co-ordinate system

- src/Native/Array.js
I believe this fixes https://github.com/elm-lang/core/issues/45.
> Change foldr's recursive call from foldl to foldr

- src/Graphics/Collage.elm
The scaling documentation was somewhat unclear about which aspect will get scaled.
Now it is specified explicitly.
> Make scale documentation explicit about the scaling

- src/Basics.elm
- src/Dict.elm
- src/Set.elm
- src/Signal.elm
- src/String.elm
This PR is meant to be very easy to merge. If there's something you don't like, let me know and I'll back it out. I added a few clarifying notes that shouldn't be too controversial and removed a reference to the nonexistent `(?)` operator. Dict and Set equality is unreliable as a point of fact and we should document it.
````elm
import Set as S
import Text (asText)
main = asText <| S.fromList [1,2] == S.fromList [2,1]
````
Again, let me know if any particular change is troublesome. Thanks.
> Trivial (hopefully) fixes to docs

- tests/elm-package.json
I'm not even sure why this wasn't causing build errors on Travis, but I had to bump this version number to run the tests locally.
> Version number bump in the tests' elm-package.json

- tests/Test/Basics.elm
I went through and added at least one test for every function defined in Basics. I used the example cases written in the documentation where available. All of these tests currently pass.
Some of these are pretty trivial tests, but I was thinking why not just add one anyway?
If this is something that you think is acceptable or worth doing, I can continue adding tests like this to other files in core.
> Add more Basics tests

- src/Graphics/Element.elm
- src/List.elm
- src/Native/List.js
- src/Signal.elm
- tests/Test/List.elm
* Changed type `List.head : List a -> Maybe a`
* Deleted `List.tail` in favour of `List.drop 1`
* Deleted `List.foldl1`, `List.foldr1`, `List.scanl1`
* Added `List.uncons`
* Changed `List.maximum` and `List.minimum` to take default values
> List does not throw runtime exceptions

- src/Graphics/Input.elm
Fixes #93.
I threw in a comment in hopes of guarding against a regression.
> Add `import Text` to fix runtime error.

- src/Array.elm
> added explicit export list to Array.elm

- src/Char.elm
> added explicit export list to Char.elm

- src/Array.elm
The documentation for `Array.get` says that the  `?` operator from the `Maybe` library makes `Array.get` easier to use when there isn't any such operator in the `Maybe` library
> Removed mention of (?) operator in documentation

- src/Native/Regex.js
- tests/Test.elm
- tests/Test/Regex.elm
See the added `Test/Regex.elm` for the example cases.  `Regex.split` seems to have been completely broken at some point.
> Fix Regex.split, and add a couple tests

- src/Native/Runtime.js
- src/Native/Signal.js
- src/Native/Time.js
making sure that events occurring in the same update cycle all get the
same timestamp;
also, making sure that timestamp (every t) will not carry events with different pair components;
this fixes issue #75
> Fix timestamp function and its interaction with every/fps/fpsWhen

- src/Native/Char.js
- tests/Test/Char.elm
This is a straight-forward fix for #50.  Simply removed the erroneous `toUpperCase` call.
Test coverage is included.
> Remove incorrect upcase from Char.toCode (fix #50)

- tests/Test/Char.elm
Added more test coverage of Char functions.  I would like these tests to be more DRY, but I was on the fence about the best (or most idiomatic) way to do that.
> Add more Char test coverage

- src/Char.elm
- src/Native/Char.js
I'm not sure if this is wanted or not, but I figure it doesn't hurt to offer.
I ported the Native.Char functions that do not use the JavaScript standard lib to pure Elm.  My reasons for doing so:
* Inspecting / understanding the implementation is easier.
* Any tooling (static analysis, optimization, test coverage) that Elm has or will have can now target these.
* If Elm itself is ever ported to another runtime, these will now be freebies.
> Port simple Char functions from JavaScript to Elm

- src/Json/Decode.elm
I think this was a copy & paste error from the docs for object2.
> Correcting the type annotation for Json-Encode.object3's docs.

- src/Native/Time.js
Fixes issue mentioned in:
https://github.com/elm-lang/core/commit/274cd7eb9a05c1b32dab563a871c557097bc3392#commitcomment-9425007
Also designed to avoid creating a new function on every frame.
> Fix incorrect delta reset in Native.Time.fpsWhen.

- src/Native/Time.js
After a good night's sleep, thought of these more descriptive function names, hopefully making clear to the reader of this function what the role of the Boolean value used there is.
@jwmerrill, what do you think of these names?
> more descriptive local function names in fpsWhen

- src/Native/Runtime.js
Without that `return`, the `localRuntime.setTimeout` in that line: https://github.com/elm-lang/core/blob/master/src/Native/Time.js#L50 doesn't give a meaningful return value, which means that the `clearTimeout` in this line: https://github.com/elm-lang/core/blob/master/src/Native/Time.js#L58 has no effect whatsoever.
This has led to buggy behavior of `fpsWhen` since at least Elm-0.13 (checked with http://share-elm.com).
> added a missing `return`

- src/Native/Time.js
fixes #139
yet another alternative to #141 and #142 
based on @jwmerrill's version of `fpsWhen`
All local state now packaged in a signal, to allow Elm Reactor to pick it up during hotswapping.
> Fix fpsWhen, including consideration for hotswapping

- src/Native/Graphics/Collage.js
This should make Elm usable on modern systems with high-resolution screens. Tested with Retina MacBook Pro 15".
Related discussion: https://groups.google.com/forum/#!topic/elm-discuss/pq1KS8XgFiQ
> Make collages resolution independent

- src/Signal.elm
Meant to keep issues/surprises/questions like https://github.com/elm-lang/core/issues/148 and https://groups.google.com/d/msg/elm-discuss/m4JB7CPXbLI/Dbac1AaAmd0J from arising.
> Improved documentation of Signal.foldp

- tests/Test/List.elm
I rewrote the List tests to be more comprehensive.  The tests now cover all exposed API functions, with the exception of `map3..5` (which were also previously not covered).  I can add coverage for `map3..5` as well as non-exposed functions, if desired.
The tests are also now parameterized, so that empty list, 1-element list, and N-element list use-cases are all covered equally.  This also enables easy stress testing, either for stack overflow checking or for benchmarking.
I tried to keep the code as clean and clear as possible.  If there are any parts that need improvement, please let me know.
> Comprehensive rewrite of List tests

- src/List.elm
- src/Native/List.js
- tests/Test/List.elm
This builds off of #150, so that should be merged first.
In the same spirit as #130, I ported several List API functions from JavaScript to pure Elm.  Some notes:
* I kept `scanl` in a separate commit because it is a tiny performance regression (1.55 -> 1.65 seconds on an old laptop for a 100k element list).  The regression is due to the requisite extra `reverse` call.
* I did not port `sortBy` in terms of `sortWith` because that resulted in a larger performance regression (2.5 -> 3.0 seconds on an old laptop for a 100k element list).  The regression is (likely) due to the extra string comparison required by the JavaScript `sortWith` implementation.  If we decide the performance penalty is worth it, I can port it also.
* There are several native functions (`any`, `drop`, `take`, `repeat`) …
>  Port List functions from JavaScript to Elm

- src/Native/Char.js
- tests/Test/Char.elm
A straight-forward fix for #73.  I just added a missing call to `Utils.chr`.
Test coverage included.
> Add missing String->Char conversion (fix #73)

- tests/Test/List.elm
I cleaned up many List tests to follow the discussion in #150.  For the most part, the only non-primitive functions the tests rely on are `foldl`, `(::)`, and `map`.  If we really wanted to be extreme we could construct a "trusted" version of `map` (and `foldr`) in terms of `foldl` and `(::)`, but that would be considerably less efficient, and I didn't want to slow the tests down.  Incidentally, these tests should run faster due to the reduction of temporary list constructions.
> Clean up List tests

- src/Native/Regex.js
- tests/Test/Regex.elm
This fix for #77 prevents empty regex matches (via e.g. `/a?/`, `/a*/`) from causing an infinite loop.  It does so by checking that the regex's `lastIndex` property increases on each call to `RegExp.exec`.
Incidentally, `RegExp.exec` sucks and mutation is evil, so I included another fix to prevent said mutation from leaking into Elm.
Test coverage is included.
> Prevent infinite loop from empty match (fix #77)

- tests/Test/Char.elm
Like #150, I rewrote the Char tests to be more comprehensive.  All exposed API functions are covered and tested with all alpha-decimal characters.  The tests are also more structured, so it is easier to add tests for future corner cases (e.g. `toLocaleLower` in a Turkish locale).
> Comprehensive rewrite of Char tests

- src/Native/Time.js
[This question](https://github.com/elm-lang/core/pull/143#issuecomment-71529672) didn't get an answer. But I think we don't actually want `timeoutId` to be part of the state that is copied over from the old signal graph to the new one on hotswap, for otherwise (in certain constellations where a hotswap occurs while a timeout is in flight on the old graph and the initialization of the new graph sets a timeout as well) we might sometimes cancel the wrong timeout (namely one affecting the old instead of the new signal graph).
Hence, the proposal to turn `timeoutId` back into a local variable.
> Don't make timeoutId in fpsWhen part of the state stored in signal graph.

- src/Graphics/Collage.elm
- src/Native/Graphics/Collage.js
- src/Text.elm
> Canvas text

- src/Native/Array.js
Array.map and Array.indexedMap have a bug that can most easily be seen
with the following use case:
EXPECTED: ```Array.empty == Array.map (\e -> e) Array.empty```
ACTUAL: ```Array.empty != Array.map (\e -> e) Array.empty```
(the same for Array.indexedMap)
This is because Array.map/Array.indexedMap initializes itself
incorrectly using:
table: new Array(a.table)  // creates a new array with an array element
instead of
table: new Array(a.table.length) // a correctly-sized array
This bug has been fixed in this commit
> Fixed bug in Array.map and Array.indexedMap

- src/Native/Runtime.js
[`console.error`](https://github.com/DeveloperToolsWG/console-object/blob/master/api.md#consoleerrorobject--object-) logs an error message to the browser console. It's supported in all browsers back to IE8.
This code could actually be simplified to only use the `console` object since it's supported in node as well: http://nodejs.org/api/console.html
The only difference from writing directly to stdout/err is the addition of newlines to every message. I can amend this PR to make that change if that sounds alright.
> Use `console.error` for `stderr` port.

- src/Basics.elm
- src/Char.elm
- src/Graphics/Input.elm
- src/Http.elm
- src/Native/Char.js
- src/Native/Regex.js
- src/String.elm
- src/Text.elm
- tests/Test.elm
- tests/Test/Char.elm
- tests/Test/Regex.elm
- tests/run-test.sh
Proposing this as an alternative to #133 as there were a lot less commits mentioning the word "fix" than I initially thought (got my git revision range wrong). So here they are cherry picked. Let's see how the CI likes it.
Happy to prune out any you don't like or add any as well, or go back to doing it more manually with #133.
> Cherry-pick for 1.1.1 attempt2

- src/Stream.elm
The current 0.15 version is broken for situations like this:
```elm
main = Varying.map Graphics.Element.show (Varying.fromStream (0,0) s)
s = let v = Mouse.position
in Stream.sample always v (Stream.fromVarying v)
```
The output is never updating! That cannot be what is supposed to happen, right?
The commit here fixes this in the way that changes the existing code of `Stream.sample` the least.
> fixing Stream.sample in Elm-0.15

- src/Stream.elm
... and renamed some type variables so that `a` and `b` in `SampleEvent` and `SampleState` correspond to the roles of `a` and `b` in the type of `sample`.
> simplified sampleUpdate in Stream.sample

- src/Native/Time.js
Done in the aftermath of https://github.com/elm-lang/core/commit/9d52af2e1c651be2474d6df997ad7ecd6765058d.
Main difference: `fps` is already defined from `fpsWhen` in `Time.elm`, so there is no need anymore to have it in `Time.js`.
Something I noticed while going through this: somewhere along the way, `Time.delay` and `Time.since` seem to have vanished. Purposefully?
> cleanup in Time.js

- src/Signal.elm
`toInt` expects a `String`, not an `Int`.
> Fix inconsistent types in `filterMap` code example.

- src/Graphics/Input/Field.elm
Removed dead mentioning of Signal.Channel in the documentation Graphics.Input.Field. Just followed the steps here:
https://github.com/elm-lang/core/issues/231#issuecomment-97546945
> Corrected dead mentioning of Signal.Channel

- tests/Test.elm
- tests/Test/Array.elm
- tests/Test/Basics.elm
- tests/Test/Bitwise.elm
- tests/Test/Char.elm
- tests/Test/CodeGen.elm
- tests/Test/Dict.elm
- tests/Test/Equality.elm
- tests/Test/List.elm
- tests/Test/Regex.elm
- tests/Test/Result.elm
- tests/Test/Set.elm
- tests/Test/String.elm
- tests/Test/Trampoline.elm
- tests/elm-package.json
This boils down to 3 things:
* Adding the `exposing` keyword multiple times per file
* Updating `elm-package.json` with the elm-version field
* Removing the tests for List.uncons which seems to have disappeared
I see that the travis build is in cabal hell, but at least you can manually run
the tests with `tests/run-test.sh` and they all pass.
> Update tests for 0.15

- src/Native/Port.js
The runtime reports `"arg is not defined"` instead of the proper error message due to the value being propagated differently after the release of 0.15.
> Fix broken error message

- src/Graphics/Input.elm
- src/Graphics/Input/Field.elm
- src/Json/Decode.elm
- src/Json/Encode.elm
Improve docs for the Json libraries, most notably
* Rename a type alias Task that has nothing to do with 0.15 Tasks
* Give an example use for `Decode.tuple1`
* Fix assorted errors, clarify wording, add information
* Give a brief introduction to what a `Decoder a` is
* Note that Infinity and NaN serialize to null (which means encode and decode aren't quite inverses)
Hopefully an easy merge - if there's anything odd, please let me know.
> Improve docs for Json.(En|De)code

- src/Basics.elm
I don't think that anyone will ever use an expression like `3^3^3`,
but it's nicer to follow the general convention.
Otherwise it would look like an oversight.
> Infix operator for exponentiation should be right-associative

- src/Graphics/Input.elm
- src/Graphics/Input/Field.elm
- src/Json/Decode.elm
- src/Json/Encode.elm
Exporting all the entities from `Graphics.Input`, `Graphics.Input.Field`, `Json.Decode`, and `Json.Encode` that are part of the documented API, i.e., all the entities that are in those files except for the "internal representations" of `Value` und `Decoder`.
Addresses https://github.com/elm-lang/core/issues/236.
> Adding missing export lists

- src/Dict.elm
The sentence made no sense. The resulting dictionary will only contain the keys that appear in the first but not in the second given dictionary. So of course, the values for those keys can only come from the first dictionary. There is no potential conflict between values, since if a key occurs in both given dictionaries, it will be dropped anyway, so there is no need to decide "by some preference" which value (from first or from second dictionary) to choose.
I found the sentence quite confusing.
> Removed sentence in `Dict.elm` documentation

- src/Dict.elm
I guess this makes it  more obvious what that code is doing, and is also more in line with how other non-auxiliary functions in this module are written.
Of course, semantically there is no change, due to this definition: https://github.com/elm-lang/core/blob/2.0.1/src/Dict.elm#L82
> Small code improvement in Dict.elm

- src/Native/Show.js
... on signals, should say "\<Signal\>", not "\<Stream\>".
Much as I regret that we don't have separate signal and stream concepts: As long as we don't, messages to the programmer/user should name the concept correctly. Currently, if you run
```elm
import Graphics.Element
main = Graphics.Element.show (Signal.constant 42)
```
you get output "\<Stream\>". But it should be (and before 0.15, was): "\<Signal\>". Streams are not a thing, currently.
> Correct behavior of `toString`

- src/Native/Graphics/Collage.js
Fixes #230.
This was breaking `Collage.textured`
> Pass redo value through to setFillStyle

- src/Native/Array.js
- tests/Test/Array.elm
This one-character change (plus test) fixes a runtime error when creating arrays of negative length with `Array.initialize` or `Array.repeat`. This behavior is now consistent with `List.repeat`.
> Fix runtime error creating arrays of negative length

- src/Set.elm
Addresses https://github.com/elm-lang/core/issues/260.
> Make `Set t` a type different from `Dict t ()`

- src/Debug.elm
Specifically, it is tempting to call `Debug.watch` directly on a signal, which is not useful though. That can lead to puzzlement, since it then seems as if `Debug.watch` serves no purpose. See [this question on the mailing list](https://groups.google.com/d/msg/elm-discuss/0fjuzWVQvOA/qxvar9TBKnAJ). The expanded documentation should make clear now that one needs to map `Debug.watch` *into* the signal if one wants to observe the value carried on the signal.
> Improve documentation of `Debug.watch`

- src/Random.elm
I added functions
> map : (a -> b) -> Generator a -> Generator b
and
> andThen : Generator a -> (a -> Generator b) -> Generator b
to the `Random` module. Is there another name you prefer to `andThen`? I was shooting for consistency with the `Maybe` module. Also, does anyone have any ideas about a uniform convention for Applicative "instances"? Currently `Random` exports `pair : Generator a -> Generator b -> Generator (a, b)`, but as far as I can tell no other module exports a function of the same name.
> Random functor monad

- src/Graphics/Collage.elm
addresses https://github.com/elm-lang/core/issues/234
> Turned Path and Shape into separate types

- src/Native/Runtime.js
Browsers use this to show the console message in red, which makes it easier to spot when you have a chatty console going.
> Use console.error when logging error messages

- src/Signal.elm
Inspired by [this thread](https://groups.google.com/forum/#!topic/elm-discuss/lg66gsMPslg), I have removed the reference to `toElement` and replaced it with the fully qualified `show`. It would have been bad enough if `toElement` didn't exist, but in fact is does exist with an incompatible type signature in the Html library.
> Docs: fix confusing example from mailing list

- src/Json/Decode.elm
IIRC [Int] was the old syntax and has been changed to List Int
> Changed documentation from [Int] to List Int

- src/Json/Decode.elm
The [docs for `Decode.dict`](http://package.elm-lang.org/packages/elm-lang/core/2.1.0/Json-Decode#dict) had an inaccurate type annotation in their code sample (showing Int instead of Float), which this fixes.
**Before:**
```elm
-- { mercury: 0.33, venus: 4.87, earth: 5.97, ... }
planetMasses : Decoder (Dict String Int)
planetMasses =
dict float
```
**After:**
```elm
-- { mercury: 0.33, venus: 4.87, earth: 5.97, ... }
planetMasses : Decoder (Dict String Float)
planetMasses =
dict float
```
> Fix type annotation in sample code for Decode.dict

- src/Native/Task.js
- Move workQueue length check out of `setTimeout`
- Quickly store a reference to `workQueue[0]` in a local variable in case `workQueue[0]` changes
Running Async tasks more frequently or increasing the `setTimeout` delay in `onComplete` increases the frequency of the exception described in #240, which suggests that the bug is indeed caused by `workQueue[0]` being overwritten with a proceeding Async task before `runTask()` can run.
I haven't observed the exception with this patch in place, even under extreme conditions with Async tasks being run one after another, milliseconds apart. Without the patch, there is a blizzard of exceptions.
Is this enough to fix the race condition? Not sure exactly how async JS works.
> Mitigate workQueue race condition (#240)

- src/Native/Date.js
- src/Native/Time.js
Fixes elm-lang/elm-repl#70 by changing a few instances of `new window.Date` to `new Date`.
> Remove use of window object in Date and Time native modules.

- src/Maybe.elm
```markdown
Transform an `Maybe` value with a given function:
```
looks like it was intended to be
```markdown
Transform a `Maybe` value with a given function:
```
in the comments so just giving it a quick adjustment.
> Fixing small `an` to `a` typo in Maybe.elm

- src/Native/String.js
... since they are not standard, thus not supported in all browsers.
Addresses https://github.com/elm-lang/core/issues/319 and thus issues like https://github.com/elm-lang/package.elm-lang.org/issues/40.
> implement trimLeft and trimRight

- src/List.elm
because this function is called 'contains' in many languages, I hit
this documentation, searched for 'contains,' and didn't find the right
method. Putting 'contains' in the description for 'member' help with this
> Change description of List.member

- src/Signal.elm
Because a new version of core may be coming out soon, this is a hopefully very simple and uncontroversial change to the docs for `Signal.forwardTo`. We remove the `port` keyword, which is wrong and misleading. Then, we define the `actions` mailbox in a reasonable way rather than just saying that is exists.
> Improve docs for Signal.forwardTo

- src/Native/Show.js
- src/Set.elm
Addresses the `Set`-related part of https://github.com/elm-lang/core/issues/288.
Before this PR, using `toString`/`show` on the following three expressions:
* `Set.fromList [1,2,3]`
* `Dict.fromList [(1,()),(2,()),(3,())]`
* `Dict.fromList [(1,1),(2,2),(3,3)]`
would lead to:
* `"Set (Set.fromList [1,2,3])"`
* `"Set.fromList [1,2,3]"`
* `"Dict.fromList [(1,1),(2,2),(3,3)]"`
After this PR, the resulting strings are:
* `"Set.fromList [1,2,3]"`
* `"Dict.fromList [(1,()),(2,()),(3,())]"`
* `"Dict.fromList [(1,1),(2,2),(3,3)]"`
> Fix how Sets and Dicts are shown

- src/Native/Graphics/Collage.js
Fixes https://github.com/elm-lang/core/issues/335.
Previously, something like
```elm
main : Signal Element
main = map (\t -> collage 500 500 [rotate (degrees t) (filled black (square 400))]) (every 20)
```
did not work since the `t` got to large for how rotation of `Shape`-`Form`s (as opposed to `Element`-`Form`s) is implemented.
> Fix rotation of shape forms

- src/Task.elm
I just found a small error in the Task documentation.
> Fixing Task.toResult documentation.

- src/Dict.elm
Replaces https://github.com/elm-lang/core/pull/255.
The essence is that calls `max (RBNode_elm_builtin c k v l r)` are replaced by `maxWithDefault k v r`, where the improvement is that the latter function is less complicated (fewer arguments, less pattern matching) and does not need an artificial (never triggered) `Debug.crash` case.
Two further notes:
* The function `min` is never called, also not exported, thus could be eliminated.
* The two functions `maxWithDefault` and `remove_max` are always called in parallel, and have the same recursion structure, so could in principle be merged into a single function.
> Algoritmic improvement in Dict

- src/Native/Regex.js
- tests/Test/Regex.elm
passing (AtMost n) behaved actually like (AtMost n+1).
Also added some test cases.
> fix Regex.replace with AtMost

- src/Native/Keyboard.js
Fixes https://github.com/elm-lang/core/issues/362 (and likely analogous issues for other signals in the `Keyboard` module).
> Fix initial value of Keyboard signals

- src/Color.elm
- src/Graphics/Collage.elm
- src/Graphics/Element.elm
- src/Random.elm
> Remove multi-way if usage, and use = for record updates.

- src/Time.elm
As per #373, makes millisecond docs simpler to understand
> Reword millisecond docs to give example of usage

- src/Native/Runtime.js
* Delete an obsolete comment
* Use stricter `typeof container.appendChild === "function"` instead of `typeof container.appendChild !== 'undefined'`
> Minor Runtime.js cleanup

- src/Maybe.elm
The current docs for [`Maybe.andThen`](http://package.elm-lang.org/packages/elm-lang/core/2.1.0/Maybe#andThen) use the example of [`String.toInt`](http://package.elm-lang.org/packages/elm-lang/core/2.1.0/String#toInt), but that function now returns a `Result` rather than a `Maybe`.
This revises the docs to use [`List.head`](http://package.elm-lang.org/packages/elm-lang/core/2.1.0/List#head) for the example instead, as it does return a `Maybe`:
```
{-| Chain together many computations that may fail. It is helpful to see its
definition:
andThen : Maybe a -> (a -> Maybe b) -> Maybe b
andThen maybe callback =
case maybe of
Just value ->
callback value
Nothing ->
Nothing
This means we only continue with the callback if things are going well. For
example, say you need to use (`head : List Int …
```
> Change `Maybe.andThen` docs to use `List.head` over `String.toInt`

- src/Char.elm
Previously existed both in `Char` and `Keyboard` modules.
Now that the next compiler version will have dead code elimination, there should be no harm in importing the alias from one into the other.
Defining `KeyCode` only in one place makes for more future-proofness.
(Also, the `KeyCode` in the type signatures in `Char` module will turn into links to the definition site in `Keyboard` module on the package site, so there's no harm in terms of documentation.)
> Avoid double definition of KeyCode alias

- src/Native/Array.js
- tests/Test/Array.elm
Make Array.indexedMap work for all array sizes, instead of hitting 1024 and wrapping around, as #271 states. Added a test case from that example to ensure that the issue is fixed in future verisons
> Make Array.indexedMap work for all array sizes

- src/Native/Utils.js
**Before:** (note the very last line)
```
Uncaught Error: Port Error:
Regarding the port named 'setParagraphs' with type:
List Quiz.Question.Paragraph
You just sent the value:
undefined
but it cannot be converted to the necessary type.
Runtime error when sending values through a port.
Expecting an array but was given 
```
**After:** (note the difference in the very last line)
```
Uncaught Error: Port Error:
Regarding the port named 'setParagraphs' with type:
List Quiz.Question.Paragraph
You just sent the value:
undefined
but it cannot be converted to the necessary type.
Runtime error when sending values through a port.
Expecting an array but was given undefined
```
> Format port errors for undefined values

- src/Mouse.elm
Until Mouse.left and Mouse.right are added as part of #43 , it makes sense for the docs on package.elm-lang.org to be true to how the function works to avoid any confusion. The examples from elm-lang should also be changed to reflect how Mouse.isDown works
> Replace Mouse.isDown docs to reflect functionality

- src/Debug.elm
- src/Graphics/Input.elm
- src/Graphics/Input/Field.elm
Several examples were still using this now outlawed signal map operator. I replaced those uses by `Signal.map`, so that the examples actually work with the current version of `core`.
> Remove <~ from documentation examples

- src/Json/Decode.elm
The purpose of this change would be to clarify the documentation for the Json.Decode `(:=)` operator.
It seems to me that the current documentation ("Decode an object if it has a certain field"), could be misleading to some people.  Consider an example JSON object, e.g.
```json
{
"username": "bob",
"password": "secret"
}
```
Then, consider the work done by something like:
```elm
"username" := string
```
The 'object' which this decodes is "bob". But, "bob" does not *have* the field 'username' -- it *is* the field 'username'. To the extent that the whole object is decoded -- that is, the object which 'has' the field 'username' -- the whole object is decoded by something like `Json.Decode.object2`. 
Also, I think that it would be helpful to specifically mention the word "fail", rather than …
> Clarify docs for the Json.Decode (:=) operator.

- src/Dict.elm
- src/Set.elm
That these functions return lists sorted in a specific way is already relied on by clients (for example by the current resolution of https://github.com/elm-lang/package.elm-lang.org/pull/97). So it makes sense to make the promise explicit.
> Documentation: Express order in Dict/Set enumeration functions

- src/Char.elm
Clarify that `Char.isUpper` and `Char.isLower` only recognize ASCII letters.
> Clarify isUpper and isLower use ASCII

- src/Time.elm
What unit is the first argument in (it is milliseconds).
> Clarify the doc for Time.every

- .travis.yml
This could shave a bit off the Travis build times.
> Travis build: use a node_js container

- src/Json/Decode.elm
This updates the decoder name in the `object3` `Json.Decode` example. I believe `point` was there previously because of the documentation for `object2`.
> Update example decoder name to match its type

- README.md
Without a branch specifier, the Travis build status badge at the top of the README show the status of the latest build, which is not very useful and may give a wrong impression of brokenness.
> Make Travis badge reflect master branch status

- src/Date.elm
23 June 1990 was a Saturday, not a Thursday
> Fix factual error in docs

- src/List.elm
adds new function toMaybeInt since String.toInt -> Result not Maybe which is need by filterMap
> updates filterMap documentation fixing example

- src/Native/Json.js
Should fix https://github.com/elm-lang/core/issues/571.
> Fix JSON array decoding in 0.17

- src/Native/Bitwise.js
Problem:
Having a bare `return` statement without a wrapping breaks a lot of build tools, because they try and load things as JS and get things wrong. These things are important to watch for build-tools, since that's how they know when packages have been upgraded and to re-run elm-make.
Solution:
Wrap the return statement with a function like the rest.
@evancz this is fairly important to be fixed before non-alpha release
> Wrap bitwise like the rest of native

- src/Task.elm
Corrections for Task module documentation.
The relevant issue #502 was:
> **Documentation suggests that `==` works on tasks, but it doesn't**
> 
> For example, the documentation of `Task.map2` (http://package.elm-lang.org/packages/elm-lang/core/3.0.0/Task#map2) contains this line:
> ```elm
> map2 (+) (succeed 9) (succeed 3) == succeed 12
> ```
> However, issuing that exact line in a program will actually evaluate to `False`. Very confusing, for example to @paparga [here](https://github.com/elm-lang/core/issues/501).
> 
> Maybe the documentation shouldn't be using `==` on tasks, and indeed maybe it should explicitly mention that `==` is wonky on tasks, as the documentation already says elsewhere about `Dict` etc.
> 
> (Note: For `Dict` etc., equality could potentially be made unwonky, but …
> Corrections for Task documentation concerning use of ==

- src/Json/Decode.elm
- When importing `Html`, if you run it, sometimes you get the error 
```	
encodeArray: _elm_lang$core$Native_Array.toJSArray,
^
TypeError: Cannot read property 'toJSArray' of undefined
```
- The problem is somewhat described in this gist here -> https://gist.github.com/ejames/2aeaf58c10d9d12fbc36aedbff4b04e1
- The problem came from `Native.Json` trying to access `Native.Array` stuff, except `Native.Array` hadn't been imported yet, meaning that it was `undefined`.
- Import `Native.Json` _last_, after `Array`, to ensure that `Native.Array` has been imported in the right order
- The problem mentioned in the gist is slightly weird. It only happens for things which have default repo urls. I don't know why that would affect it, but this makes it work for all cases.
- You can force the Array to …
> move Native.Json import to be after all other imports

- src/Native/Json.js
In 0.17, decoding integer values larger than 2147483647 from JSON fails:
`UnexpectedPayload "Expecting an Int at _.foo.bar but instead got: 2934520482"`
This change seems to fix the issue. It's basically reverting to the logic used in 0.16 with the return values changed to match the API used in 0.17.
> Accept large integer values in JSON decoders

- src/Platform/Cmd.elm
Simplest typo I discovered while teaching Elm... I thought I'd just send a PR 😅 
Thanks!
> Cmd.elm: Fix typo in doc

- src/String.elm
Example for String.toLower in documentation
at package.elm-lang.org is missing syntax highlighting
due to misaligned docstring.
(look at screenshot)
> Fix docstring for String.toLower

- src/Dict.elm
- tests/Test/Dict.elm
I added tests that demonstrate the problem. In particular, the "merge singletons in order" and "partially overlapping" tests will fail without the changes to Dict.merge.
> Fix Dict.merge problem where some elements ignored from second dict

- src/Random.elm
As I mentioned in my comment in issue #635, I think the constant we're using needs to be amended. The [Haskell implementation](http://hackage.haskell.org/package/random-1.0.1.1/docs/src/System-Random.html#RandomGen) uses that value:
```
mkStdGen32 sMaybeNegative = StdGen (s1+1) (s2+1)
[...]
s2      = q `mod` 2147483398
stdNext (StdGen s1 s2) = (fromIntegral z', StdGen s1'' s2'')
[...]
s2'' = if s2' < 0 then s2' + 2147483399 else s2'
stdSplit std@(StdGen s1 s2)
[...]
new_s2 | s2 == 1          = 2147483398
[...]
```
The same value is mentioned in the [original paper](http://webhome.csc.uvic.ca/~wkui/Courses/CSC446/CLCG.pdf).
> For 32-bit computers, we suggest l= 2, m1 = 2147483563, a1 = 40014, m2 = 2147483399 and a2 =
> 40692.
I am by no means expert on pseudo-random number generators, so I …
> Amended constant value used by the pseudo-random number generator

- tests/Test/Equality.elm
The purpose of these is to expose, to testing, any special case treatment surrounding the record field name `ctor`. See https://github.com/elm-lang/core/issues/652, which observed a bug in this.
> Add tests for equality, concerning records

- src/Native/Json.js
- tests/Test/Json.elm
#639 was closed because @evancz came across the same issue and fixed it in the same way, adding some useful context information. This PR extends the test from #639 to fit his implementation. It also changes the error message to use the function name `customDecoder`, which was misspelled as @jvoigtlaender points out in https://github.com/elm-lang/core/commit/7f6e518378ec354681ef6337d5dfa8182b2e8fca
> Add test for customDecoder messages and fix typo in messages

- src/List.elm
- tests/Test/List.elm
This is a follow up to #659. We are looking for a way of implementing `List.take` that doesn't run the risk of a stack overflow and has good performance over as wide a domain as possible. My previous PR failed the second criterion, but after taking a look at [this post](https://blogs.janestreet.com/optimizing-list-map/), I think I have found something that has acceptable performance.
Would love to get some feedback on this!
The Fast Way
---------
`takeFast` is similar to the current version of `take` with a bit of loop unrolling. This means that we don't do quite as much recursion, so it can handle larger values of `n` without crashing. It is also slightly faster than the current implementation.
I expected that unrolling the loop 4 times would have raised the limit on `n` by a factor of …
> Use tail-recursive version of List.take at large n

- src/Native/String.js
- tests/Test/String.elm
The `String.indexes` function enters an infinite loop when doing  `String.indexes "" "Some string"`, this is because the `i` variable is no advanced on each step of the loop since it will always return 0.
I chose to return an empty list for this cases, as I think it is the most sensible thing to do IMO, but another valid interpretation is that the empty string is contained in all of the indexes of the string.
In case the second interpretation is preferred, I can gladly change it :)
> Avoiding infinite loop when the search string is empty

- tests/Test/Basics.elm
To ensure that no regression will sneak in against the semantic improvement from `4.0.3`.
> Add test for dict equality

- src/Native/Platform.js
This PR demonstrates one possible way to deal with calls to send prior to incoming ports being ready ( #595 ). As @artisonian mentioned, `send` can be called before `onEffects` in the port effect manager is called, so there are no `Sub`s around to handle the send. This fix demonstrates queuing things that are sent until `onEffects` has been called for the first time, and then pushing all enqueued values through during that first call.
By @yjkogan and myself.
We demonstrated that this fixes the issue in https://github.com/lukewestby/elm-port-bootup-sscce
> Candidate fix for #595

- src/Native/Platform.js
It's possible that someone can unsubscribe from a port in JavaScript in the same tick that the port's subscription callback is called. Since the array that stores these subscription callbacks is shared and mutated in place by `subscribe` and `unsubscribe` that unsubscribing in the same tick as a callback can cause the following subscription to be skipped. This is all demonstrated and explained in #712.
See https://github.com/reactjs/redux/blob/master/src/createStore.js#L63-L67
This fix solves that issue by making the subs array immutable with respect to unsubscribing and iterating. When a subscription callback drops itself the subs array will be cloned before the callback is spliced out. Then, during iteration when a message comes in a separate reference is made to the subs array so that …
> Fix for #712 - don't skip next sub if previous sub unsubscribes itself

- src/Array.elm
The exemple wasn't really crystal clear, because it could be understood as : find the element 1 from the list [0, 1] and returns it. As soon as you understand it's an index (by the exemple) everything goes easier.
> Improve the Array get exemple

- src/Native/Utils.js
The current implementation performs a lookup in `updatedFields` for every key in `oldRecord`. As `updatedFields` is likely to contain fewer keys than `oldRecord`, the number of lookups can actually be reduced by iterating both objects, instead of just one.
According to the benchmark from the following gist, the performance increase can be quite noticeable (2-3x):  https://gist.github.com/Skinney/51b42ac2c4df1776d7a77e401b7477c4
Benchmark numbers:
```
➜  node index.js
original x 936,987 ops/sec ±1.31% (85 runs sampled)
new x 2,813,038 ops/sec ±2.08% (79 runs sampled)
```
This benchmark shows the result of updating an object of six keys, with an object of one key. The benchmark still shows a significant speed increase when updating four out of six keys.
> Optimize update fn

- src/Native/Regex.js
- tests/Test/Regex.elm
> Reset `lastIndex` in `Regex.split` so that it is idempotent.

- src/Native/Regex.js
- tests/Test/Regex.elm
> Set the `index` parameter accurately in Regex.replace.

- .gitignore
- tests/Main.elm
- tests/Test/Array.elm
- tests/Test/Basics.elm
- tests/Test/Bitwise.elm
- tests/Test/Char.elm
- tests/Test/CodeGen.elm
- tests/Test/Dict.elm
- tests/Test/Equality.elm
- tests/Test/Json.elm
- tests/Test/List.elm
- tests/Test/Regex.elm
- tests/Test/Result.elm
- tests/Test/Set.elm
- tests/Test/String.elm
According to https://github.com/elm-lang/core/pull/771#discussion_r90767868 I suggest to reformat test according to `elm-format` standard. I think it's best time to do it right now before this make any conflicts in PRs.
- Run `elm-format` for all test files.
- remove `node_modules` from `.gitignore`
> elm-fromat for tests

- tests/Test/Basics.elm
The purpose of these is to expose, to testing, any special case treatment surrounding the record field name `ctor`. See https://github.com/elm-lang/core/issues/654, which observed a bug in this.
> Add tests for toString, concerning records

- src/Native/Platform.js
Suppose we have a bad port invocation that's going to blow up, in a file called `index.html`:
```js
function invokeBustedPort() {
app.ports.foo.send(null);
}
// alternatively, for a post-init error: setTimeout(invokeBustedPort, 500);
invokeBustedPort();
```
The stack trace doesn't include the offending function, `invokeBustedPort`, or a useful line number indicating where the function was invoked:
Now it includes both!
The basic idea is to do the decoder check immediately inside `send`, and `throw new Error` inside `send` so it preserves the best stack trace information.
This means that in the `preInit` case it fails slightly sooner, because it does the check before init - and then defers the actual value sending - instead of deferring both.
> Improve stack traces for port errors

- tests/Main.elm
- tests/Test/Maybe.elm
There are no unit tests for the public functions of the `Maybe` module. This makes it impossible to apply refactoring to the existing code without knowing whether this will break the expected behaviour.
Also, unit tests are good examples on how to use an API. All public functions should have [unit tests](https://github.com/elm-lang/core/blob/master/CONTRIBUTING.md#bug-fixes).
Add unit tests.
> Adding Unit Tests for Maybe

- tests/Test/Basics.elm
- tests/Test/CodeGen.elm
Add some more tests which also serve as regression tests for parser bugs.
> More tests

- src/Native/Utils.js
It's lovely when `elm-repl` prints out a `<function>` signature for me:
```
> List.map
<function> : (a -> b) -> List a -> List b
```
It's less lovely when the `<function>` value includes the internal name of the JavaScript function:
```
> negate
<function:negate> : number -> number
> (\x -> x + 1)
<function:d_e_l_t_r_o_n_3_0_3_0> : number -> number
> import PhotoGroove exposing (Msg(..))
> SetHue
<function:_user$project$PhotoGroove$SetHue> : Int -> PhotoGroove.Msg
```
It really seems like it would be better if all function values displayed as `<function>` and that's it.
This PR makes that happen. If this solution is undesirable for some reason I'm missing, I'd be happy to close this PR and open an issue about the UX problem instead.
> Never show function names in toString

- .gitignore
- src/Native/String.js
- tests/Test/String.elm
With some parser work I’m doing, I wanted to expand the set of numbers that Elm can easily turn into `Int` and `Float` values.
- `String.toFloat` accepts scientific notation like `1e+40`
- `String.toInt` accepts hex like `0xBEEF`
- Added a bunch of tests for these things
> Improve String.toInt and String.toFloat

- CONTRIBUTING.md
This should lower the bar for people to actually follow the direction of putting proposed new functionality into `*-extra` packages first. They then know they don't have to create their own mini packages for that, but can instead contribute to packages already maintained by community members at https://github.com/elm-community.
> Point to the elm-community GitHub organization in CONTRIBUTING.md

- tests/Main.elm
- tests/Test/Tuple.elm
Simplest tests you will ever see! :)
> Add unit tests for Tuple

- src/Native/String.js
Currently `String.toInt` can return a `Float`, as the JavaScript function `parseInt` will return `NaN` (which is type `Float` in Elm) if you supply it with '+' or '-'. This will get around the type checker, so the compiler will think that the 'NaN' is an `Int`. See #831 for more details of the bug.
I've added a new condition so that an error will be raised if the input string is a single '-' or '+' character.
If you'd like to check the logic, I've mocked it up on [repl.it](https://repl.it/F5ol/0).
> Added extra condition to stop '-' or '+' returning a `Float` from `String.toInt`.

- tests/Test/Set.elm
Unit tests for each function exposed by Set module
If you feel there is too much redundancy in the tests, please let me know and I will trim them a bit.
(on the other hand I feel that many of these should be fuzz tests, but I didn't see fuzz testing used anywhere else in core, so decided to stick with unit testing for now)
> Add tests for Set

- src/Array.elm
- src/Elm/Kernel/JsArray.js
- tests/Test/Array.elm
Includes test to reproduce issue.
The first problem was that depth calculation when slicing down to a one element array (slice 0 1 array) would return `NaN`, which is a setup for failure.
The second problem was the assumption that `hoistTree` always would be called with a tree with a size of > 1.
> Dev: Fixes runtime crash when slicing a large array so it becomes small (< 32 elements)

- src/Elm/Kernel/JsArray.js
`_JsArray_newArray` was introduced because it had a noticeable performance impact in Safari. In recent benchmarking, this no longer seems to be the case. Removing this function saves some bytes while improving performance in Chrome. Safari is unaffected. Firefox loses some performance, but not nearly as much performance as Chrome gains.
`_JsArray_initializeFromList` has been altered so that it is no longer necessary with an if-statement in the body of the for-loop. This makes it easier for Chrome to optimize. As such, converting a List to an Array is now 6x faster in Chrome. Minor performance improvements in Safari and Firefox.
`_JsArray_unsafeSet` has been rewritten to manually copy the array instead of using .slice. This improves performance in both Safari and Chrome. There is some …
> Improve performance, and reduce code size, for JsArray.

- src/Random.elm
As requested. Also includes some very minor revisions to docs and removes the `mul32` function that was never called.
I copied the file to a separate directory and it compiled, but extra eyes to make sure I didn't do anything stupid would be great.
And thank you so much for merging the previous PR!
> Remove |> and <| from the Random module.

- src/Elm/Kernel/Char.js
> [0.19] Char.fromCode - typo

- src/Random.elm
This adds `Random.independentSeed`, which allows the creation of random
seeds that are completely independent of each other. No amount of taking
random numbers from one seed will "wind" it to the same place as
another, such that they produce the same values.
This feature is essential to elm-test's ability to reproduce failures
because it allows each fuzz test to consume as many random values as it
needs without affecting tests that run after it. It means we can run
failing tests alone without disturbing the failure. It also makes it
possible to parallelize test runs.
If this PR is merged, elm-test will be able to use core's Random
implementation instead of my third party library. cc @rtfeldman
> Make it possible for elm-test to use core's Random

- src/Dict.elm
This new implementation is a drop-in replacement, offering faster inserts (~170% increase) and faster removals (~30% faster).
The code is also compiles to less js. Recent testing shows that this implementation produces 488 less bytes after minification and gzip.
I've made as few changes to the original code as possible.
> New Dict implementation using Left-Leaning RB-Trees.

- src/Basics.elm
- src/Char.elm
See its Wiktionary [entry](https://en.wiktionary.org/w/index.php?oldid=49742097&title=hexadecimal).
> Spell hexadecimal correctly

- src/Elm/Kernel/Utils.js
Fix a "truthiness" bug in the PROD version of `_Utils_cmp`
[This line](https://github.com/elm/core/blob/master/src/Elm/Kernel/Utils.js#L104) wants to check if the first argument is a Tuple. In PROD mode it uses `if (!x.$)` to check for falsiness, since tuples have no `$` property in PROD mode.
Unfortunately `_List_Nil` can also be passed in here, which is represented as `{ $: 0 }`. When that happens, `x.$` _exists_, but since it is falsy it passes the condition and is misidentified as a tuple! The tuple-related code then runs even though the inputs are lists. This can produce incorrect results, such as in the SSCCE below.
This PR fixes it by using `hasOwnProperty` instead of a truthiness check.
(There are, of course, lots of ways to check for missing properties. Not sure what your …
> Fix optimized `compare` when first arg is Nil

- tests/run-tests.sh
This reduces the time it takes to "seed" the test, by reducing fuzz tests to a minimum.
It also passes along the arguments to `elm-test`. So `run-tests.sh --watch` => `elm-test --watch`.
> Improve run-tests.sh

- .travis.yml
- tests/elm.json
- tests/run-tests.sh
This commit contains a few minor changes to the bash script used to run tests.
This means that CI runs using elm 0.19.1 can still show as green.
cc: @jerith666 and @Skinney
> test: fix test runner for elm 0.19.1

- tests/run-tests.sh
so that arguments containing spaces aren't split up
> run-tests.sh: fix argument passing to use proper quoting

- src/Elm/Kernel/Utils.js
- tests/tests/Test/Equality.elm
This has the same solution as #1018, but uses fuzz testing instead of unit tests. This PR is also not conflated with upgrading the testing code for 0.19.
> Fixes runtime exception when comparing inequal lists with over 100 elements

- src/List.elm
I want to thank Evan and the community for such a great and growing language! These two spaces stood out a little, so I rolled in the pull request.
> Removed extra space after the arrow

- src/Elm/Kernel/Platform.js
Add missing scope declaration on `result` variable.
The underlying issue caused by the missing scope declaration is that some tasks are not performed during synchronous event processing (more details on the listed issues below).
This fixes the following issues:
* elm/virtual-dom#146
* elm/virtual-dom#152
> fix missing scope declaration on variable

- hints/11.md
I just ran into a runtime error caused by calling `Basics.modBy` with the arguments in the wrong order, leading to a value of 0 as the first argument. The error had a link to [the 1.0.0 version of the page i edited](https://github.com/elm/core/blob/1.0.0/hints/11.md). My understanding is that `%` has been removed from the language, in favor of `remainderBy` and `modBy`, so, given that the old version of the page would still be around for old versions of elm, changing this to reference `modBy` seems better. 
As mentioned in [this issue comment](https://github.com/elm/core/issues/1034#issuecomment-503159937), `remainderBy 0 n` currently returns `NaN` instead of leading to this page, so I didn't mention it.
> replace refernce to `%` with `modBy`

- README.md
Some had spaces around the imported type, some don't.
This makes the imports consistent, by removing the spaces in the ones
that had them.
> Make the imports in the prelude consistent
