.gitignore, .travis.yml, tests/elm-io-ports.js, tests/elm-package.json, tests/run-test.sh
Makes it easy to run the tests locally.
=> run-test.sh script

src/Native/Mouse.js
=> fixed wrong projection in Mouse.js

src/Signal.elm
to address this question: https://groups.google.com/d/msg/elm-discuss/Yo0KXZPLK9o/LAwlwDZiVDQJ
=> clarified docu of Signal.merge

src/Text.elm
Just some tiny spelling errors I noticed while reading :smile:
=> Fix some small typos in the Text docs.

src/Trampoline.elm
=> added explicit export list to Trampoline.elm

src/Window.elm
=> added explicit export list to Window.elm

src/WebSocket.elm
=> added explicit export list to WebSocket.elm

src/Color.elm
=> added explicit export list to Color.elm

src/Touch.elm
=> added explicit export list to Touch.elm

src/Debug.elm
=> added explicit export list to Debug.elm

src/Mouse.elm
=> added explicit export list to Mouse.elm

src/Time.elm
=> added explicit export list to Time.elm

src/Text.elm
=> added explicit export list to Text.elm

src/String.elm
=> added explicit export list to String.elm

src/Result.elm
=> added explicit export list to Result.elm

src/Signal.elm
=> added explicit export list to Signal.elm

src/Regex.elm
=> added explicit export list to Regex.elm

src/List.elm
=> added explicit export list to List.elm

src/Keyboard.elm
=> added explicit export list to Keyboard.elm

src/Http.elm
=> added explicit export list to Http.elm

src/Date.elm
=> added explicit export list to Date.elm

src/Bitwise.elm
=> added explicit export list to Bitwise.elm

src/Basics.elm
=> added explicit export list to Basics.elm

tests/Test.elm, tests/Test/Bitwise.elm
=> Add Bitwise tests

src/Time.elm
In particular addressing uncertainty about independent calls of timer functions expressed in https://github.com/elm-lang/core/issues/145 but also reoccurringly on the mailing list.
=> Improving docu in `Time` module.

src/Http.elm, src/Json/Encode.elm
Fix typo in `Json/Encode.elm` and unify capitalization in `Http.elm`.
=> Improve documentation

src/Native/Signal.js
Should fix [this problem](https://groups.google.com/d/msg/elm-discuss/r6EJjbQ6V0E/5gnwN9KljToJ).
=> make sure genericMerge nodes have an initial value

src/Graphics/Input.elm
Just removed dead mentioning of Signal.Channel in the documentation Graphics.Input. Literally followed the steps here:
https://github.com/elm-lang/core/issues/231#issuecomment-97546945
=> Updated Graphics.Input.elm's documentation

src/Array.elm, src/Dict.elm, src/Set.elm
See @evancz's comments on #251.
=> O(1) methods for Array.isEmpty, Dict.isEmpty, and Set.isEmpty

changelog.md
=> Fix the changelog

changelog.md
The question came up in [this thread](https://groups.google.com/d/msg/elm-discuss/MNZgNC-2wWI/28znhHgKpRsJ).
=> Mention what happened to Text.plainText

tests/Test/Char.elm
`assertEqual (False) (List.all ...)` -> `assertEqual (False) (List.any ...)`
=> Logic issue in tests for Char

src/Time.elm
Because of this discussion: https://groups.google.com/d/msg/elm-discuss/1Z5xvqr0uY4/-qgrgsMkLEcJ
=> Clarify semantics of Time.delay in documentation

src/Native/Graphics/Element.js
Fix remnants of a shelved refactor
=> documentCreateElement -> document.createElement

src/Dict.elm, src/Native/Show.js, src/Set.elm
Finishes cleanup for https://github.com/elm-lang/core/issues/288
=> Rename constructors handled "specially" in toString

src/Json/Decode.elm
Fixes https://github.com/elm-lang/core/issues/364.
=> Fix the example for "crazily formatted data"

src/Graphics/Collage.elm
=> Reword docs for move to reflect order of args

src/Basics.elm, src/Bitwise.elm, src/Color.elm, src/Dict.elm, src/Graphics/Input.elm, src/Json/Decode.elm, src/Random.elm, src/String.elm
Fix spelling of:
* arithmetic
* arranged
* associated
* implementation
* primarily
* explicitly
* menu
Capitalize proper nouns:
* Cartesian
=> Fix spelling/capitalization of various words

src/Json/Decode.elm
=> Error in docs

src/Maybe.elm
=> Fix a link in docu

src/Graphics/Collage.elm
Motivation for the change is here: https://github.com/elm-lang/core/pull/392#issuecomment-138097389.
=> Improve collage documentation

src/Signal.elm
Trying to pick up lessons from this discussion: https://github.com/elm-lang/core/pull/392.
=> Improve merge documentation

src/Platform/Sub.elm
just a simple text edit on the second sentence of the first paragraph
=> add missing word

.travis.yml
This config makes Travis builds run faster. Cribbed from `elm-community/elm-test`.
=> Give Travis all the latest improvements

src/List.elm
=> Give foldl and foldr equivalent examples

src/Task.elm
This probably should not come up in any realistic scenario, but then again, it's just one less thing that can go wrong.
=> `sequence` is not stack-safe

src/Basics.elm
=> Remove reference to 7-tuples in docs

src/Elm/Kernel/Utils.js
Sorry @evancz there was a syntax error in the PR you just merged from me!
I didn't notice the extra paren because it's in commented-out code so it didn't get highlighted!
=> Fix typo in merged PR #975

README.md, hints/5.md
Use HTTPS links where possible.
=> Switch to HTTPS links
